### ISSUE TITLE
Missing Example

### ISSUE THREAD

**Issue by netmindz** [rorosaurus/esp32-hub75-driver#7]
Can you provide a complete, ultra simplistic example that is known to work with the ESP32 and your shield? 

As this is the first time I'm trying to use the ESP32 rather than Teensy with SmartMatrix, I'm not sure if the issues I'm seeing relate to something wrong with my build of the shield or the code I'm using on the ESP32

I'm just getting very dim flickering. I've only soldered up the first of the 5 boards I ordered in mode1, no extra components. ESP32 on USB PSU and panel on it's own PSU. I see no reference to needing common ground or similar. I can't see any bad solder joints or anything

**Comment by netmindz** [comment]
See attached video

**Comment by netmindz** [comment]
https://photos.app.goo.gl/L9qYpiK7yQrj6Kno6

**Comment by netmindz** [comment]
The examples referenced don't work as they are for older version of SmartMatrix

**Comment by davemaster** [comment]
Here in this [link](https://github.com/pixelmatix/SmartMatrix/tree/teensylc/examples), are many examples.... I tested that library with my ESP32 DOIT kit V1

Best regards

**Comment by netmindz** [comment]
Thanks for the link, but that's for an out of date version of Smartmatix

**Comment by rorosaurus** [comment]
That branch of SmartMatrix is the only one with ESP32 support, AFAIK! So that's the only one I've used for my projects.

**Comment by netmindz** [comment]
update: had luck with with mode0 direct to panel setup using a new pcb
